/**
 * Write the shared test vectors.
 *
 * The TypeScript tests read `vectors.json`. The Foundry tests read the same file. Both
 * test suites must accept the same values. This match proves that the two
 * implementations agree.
 *
 * Run `npm run vectors` after every change to the crypto code.
 */

import { writeFileSync } from "node:fs";
import {
  type Domain,
  blind,
  blindSign,
  dst,
  g2ToBytes,
  hashToG2,
  mintKey,
  splitGreedy,
  toHex,
  unblind,
  verify,
} from "./src/index.ts";

const DOMAIN: Domain = { chainId: 5042002, contract: "0x00000000000000000000000000000000000000c0" };

const USDC = 1_000_000n;

const KEYS = [
  { denom: 1n * USDC, sk: 0x2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2an },
  { denom: 10n * USDC, sk: 0x3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3bn },
  { denom: 100n * USDC, sk: 0x5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5dn },
].map((k) => mintKey(k.denom, k.sk));

const NOTES = [
  { address: "0x1111111111111111111111111111111111111111", r: 0x4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4cn, keyIndex: 0 },
  { address: "0x2222222222222222222222222222222222222222", r: 0x6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6en, keyIndex: 1 },
  { address: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef", r: 0x5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5an, keyIndex: 2 },
];

const notes = NOTES.map((n) => {
  const key = KEYS[n.keyIndex];
  const { blinded, r } = blind(n.address, DOMAIN, n.r);
  const blindSig = blindSign(key, blinded);
  const sig = unblind(blindSig, r);
  if (!verify(key.pk, n.address, sig, DOMAIN)) throw new Error(`vectors: ${n.address} does not verify`);
  return {
    address: n.address,
    denom: key.denom.toString(),
    keyIndex: n.keyIndex,
    r: toHex(r),
    hashToG2: toHex(g2ToBytes(hashToG2(n.address, DOMAIN))),
    blinded: toHex(blinded),
    blindSig: toHex(blindSig),
    sig: toHex(sig),
  };
});

const vectors = {
  note: "Generated by generate-vectors.ts. Do not edit by hand.",
  // Foundry cannot measure a JSON array, so the counts are explicit.
  counts: { keys: KEYS.length, notes: NOTES.length },
  domain: { chainId: DOMAIN.chainId, contract: DOMAIN.contract, dst: toHex(dst(DOMAIN)) },
  keys: KEYS.map((k) => ({ denom: k.denom.toString(), sk: `0x${k.sk.toString(16).padStart(64, "0")}`, pk: toHex(k.pk) })),
  notes,
  splits: [111n * USDC, 100n * USDC, 1n * USDC].map((amount) => ({
    amount: amount.toString(),
    split: splitGreedy(amount).map((d) => d.toString()),
  })),
};

writeFileSync("vectors.json", `${JSON.stringify(vectors, null, 2)}\n`);
console.log(`vectors.json written: ${notes.length} notes, ${KEYS.length} keys`);
